### ISSUE TITLE
Error in imgLoader/transform.py?

### ISSUE THREAD

**Issue by BostonLobster** [tfygg/pytorch-tutorials#2]
In imgLoader/transform.py, you wrote
>
    transforms.Normalize(mean = (1, 1, 1), std = (2, 2, 2))#range [-1.0,1.0] -> [0.0,1.0]

But shouldn't the mean be `(-1, -1, -1)`, so that `(input - mean)/std` outputs [0.0, 1.0]?

**Comment by tfygg** [comment]
> In imgLoader/transform.py, you wrote
> 
> > 
> 
> ```
> transforms.Normalize(mean = (1, 1, 1), std = (2, 2, 2))#range [-1.0,1.0] -> [0.0,1.0]
> ```
> 
> But shouldn't the mean be `(-1, -1, -1)`, so that `(input - mean)/std` outputs [0.0, 1.0]?

Thank you for your attention.
Please make the pull request.

**Comment by BostonLobster** [comment]
I have made the pr :)
